services:
  otel-collector:
    build:
      context: ./otel-collector
    ports:
      - "4318:4318"
    env_file:
      - .env
    environment:
      - ELASTIC_ENDPOINT=${ELASTIC_ENDPOINT}
      - ELASTIC_TOKEN=${ELASTIC_TOKEN}
    command: ["--config=/etc/otelcol/config.yaml", "--set=service.telemetry.logs.level=debug"]

  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    ports:
      - "8123:8123"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - otel-collector