receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlp/elastic:
    endpoint: ${ELASTIC_ENDPOINT}
    headers:
      Authorization: ${ELASTIC_TOKEN}
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic, debug] 
