receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlp/elastic:
    endpoint: 
    headers:
      Authorization: 

  debug:  # ✅ Use this instead of the deprecated 'logging'
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic, debug]  # ✅ Reference debug exporter here
